import {packages,packageRules,priceLabel} from '../content/business';
import {today,initialBooking,validateEvent,validateContact,needsCustomization,summaryPairs,makeMessage,whatsappURL,type Booking,type Errors} from '../lib/booking';
const form=document.querySelector<HTMLFormElement>('#booking-form')!;
const panel=document.querySelector<HTMLElement>('#booking-panel')!;
let step=1;
let message='';
type Control=HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement;
const field=(name:string)=>form.elements.namedItem(name) as Control;
function read():Booking {
  const values={} as Record<string,string|boolean>;
  ['evento','paquete','fecha','hora','personas','servicio','modalidad','lugar','nombre','responsable','telefono','notas'].forEach(key=>values[key]=field(key).value);
  values.consentimiento=(field('consentimiento') as HTMLInputElement).checked;
  values.personalizar=(field('personalizar') as HTMLInputElement).checked;
  return values as Booking;
}
Object.entries(initialBooking(new URLSearchParams(location.search))).forEach(([key,value])=>field(key).value=String(value));
(field('fecha') as HTMLInputElement).min=today();
function clearErrors(){form.querySelectorAll<HTMLElement>('.field-error').forEach(el=>el.textContent='');form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));document.querySelector<HTMLElement>('#form-error')!.hidden=true;}
function showErrors(errors:Errors){clearErrors();const entries=Object.entries(errors);if(!entries.length)return false;for(const [key,error] of entries){document.querySelector('#error-'+key)!.textContent=error!;field(key).setAttribute('aria-invalid','true');}const summary=document.querySelector<HTMLElement>('#form-error')!;summary.hidden=false;summary.textContent='Revisa tu consulta: '+entries.map(([,error])=>error).join(' ');field(entries[0][0]).focus();return true;}
function customization(){const needed=needsCustomization(read());document.querySelector<HTMLElement>('#customization')!.hidden=!needed;if(!needed)(field('personalizar') as HTMLInputElement).checked=false;}
function updatePackage(announce=false){const p=packages.find(p=>p.id===field('paquete').value);const rule=packageRules(p);const hint=document.querySelector<HTMLElement>('#package-hint')!;(field('personas') as HTMLInputElement).min=String(rule.minPeople);hint.hidden=!p;if(p){hint.textContent=`${p.name}: ${rule.minPeople>1 ? 'mínimo '+rule.minPeople+' personas en total' : 'para una protagonista; personas extra bajo cotización'}. ${announce ? 'Actualizamos ocasión y servicios. Revisa los datos antes de continuar.' : 'Puedes solicitar cambios bajo cotización.'}`;}customization();}
updatePackage();
field('paquete').addEventListener('change',()=>{const p=packages.find(p=>p.id===field('paquete').value);if(p){const rule=packageRules(p);field('evento').value=rule.event;field('servicio').value=rule.service;if(Number(field('personas').value)<rule.minPeople)field('personas').value=String(rule.minPeople);}clearErrors();updatePackage(true);});
['evento','servicio'].forEach(key=>field(key).addEventListener('change',customization));
function go(next:number,focus=true){step=next;clearErrors();panel.querySelectorAll<HTMLElement>('[data-step]').forEach(el=>{const active=Number(el.dataset.step)===step;el.hidden=!active;if(el instanceof HTMLFieldSetElement)el.disabled=!active;});panel.querySelectorAll('.form-progress li').forEach((li,i)=>{li.classList.toggle('current',i+1<=step);if(i+1===step)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current');});const xv=field('evento').value==='quinceanero';document.querySelector<HTMLElement>('#responsible-field')!.hidden=!xv;(field('responsable') as HTMLInputElement).required=xv;if(focus)panel.querySelector<HTMLElement>(`[data-step="${step}"] h2`)!.focus();}
panel.querySelectorAll<HTMLButtonElement>('[data-go]').forEach(button=>button.addEventListener('click',()=>go(Number(button.dataset.go))));
form.addEventListener('submit',event=>{event.preventDefault();const booking=read();(field('fecha') as HTMLInputElement).min=today();if(step===1){if(showErrors(validateEvent(booking)))return;go(2);}else if(step===2){const eventErrors=validateEvent(booking);if(Object.keys(eventErrors).length){go(1);showErrors(eventErrors);return;}if(showErrors(validateContact(booking)))return;message=makeMessage(booking);renderSummary(booking);go(3);}});
function textElement(tag:string,text:string){const el=document.createElement(tag);el.textContent=text;return el;}
function renderSummary(booking:Booking){const summary=document.querySelector('#booking-summary')!;summary.replaceChildren();summaryPairs(booking).forEach(([key,value])=>{const row=document.createElement('div');row.append(textElement('dt',key),textElement('dd',value));summary.append(row);});const p=packages.find(p=>p.id===booking.paquete);const packageSummary=document.querySelector<HTMLElement>('#package-summary')!;packageSummary.hidden=!p;packageSummary.replaceChildren();if(p){packageSummary.append(textElement('h3',p.name),textElement('p',priceLabel(p)));const list=document.createElement('ul');p.includes.forEach(item=>list.append(textElement('li',item)));packageSummary.append(list,textElement('p','Se cotiza por separado: '+p.excludes.join(', ')+'.'));if(booking.personalizar&&needsCustomization(booking))packageSummary.append(textElement('p','Solicitas adaptar esta experiencia. La propuesta confirmará el alcance y los adicionales.'));}
document.querySelector('#prepared-message')!.textContent=message;
const url=whatsappURL(message);const link=document.querySelector<HTMLAnchorElement>('#whatsapp-link')!;link.hidden=!url;if(url)link.href=url;else link.removeAttribute('href');document.querySelector('#destination-note')!.textContent=url ? 'Abrirás WhatsApp con el mensaje preparado. Debes enviarlo para que el equipo reciba tu consulta. La consulta no confirma una reserva.' : 'El WhatsApp del negocio aún no está configurado. Puedes copiar tu consulta; no se enviará a ningún destinatario.';document.querySelector('#copy-status')!.textContent='';}
document.querySelector('#whatsapp-link')!.addEventListener('click',()=>document.querySelector('#copy-status')!.textContent='WhatsApp abierto. Envía el mensaje desde WhatsApp para compartir tu consulta.');
document.querySelector('#copy-message')!.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(message);document.querySelector('#copy-status')!.textContent='Consulta copiada. No se ha enviado ningún mensaje.';}catch{document.querySelector('#copy-status')!.textContent='No se pudo copiar automáticamente. Selecciona y copia el texto del mensaje.';document.querySelector<HTMLDetailsElement>('#message-details')!.open=true;const el=document.querySelector<HTMLElement>('#prepared-message')!;el.focus();const range=document.createRange();range.selectNodeContents(el);const selection=window.getSelection();selection?.removeAllRanges();selection?.addRange(range);}});
go(1,false);
