import {test,expect} from '@playwright/test';
import {packages,packageRules} from '../src/content/business';
import {today,makeMessage,whatsappURL,validateEvent,validateContact,initialBooking,type Booking} from '../src/lib/booking';
const routes=['/','/servicios','/servicios/maquillaje','/servicios/peinado','/servicios/eventos','/novias','/quinceaneras','/galeria','/paquetes',...packages.map(p=>'/paquetes/'+p.id),'/nosotros','/contacto','/reservar','/preguntas-frecuentes','/privacidad','/condiciones'];
test('22 rutas directas, enlaces internos, metadatos e imágenes',async({page,request})=>{
 expect(routes).toHaveLength(22);const targets=new Set<string>();const titles=new Set<string>();const descriptions=new Set<string>();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 for(const route of routes){const response=await page.goto(route);expect(response?.status(),route).toBe(200);await expect(page.locator('h1')).toHaveCount(1);titles.add(await page.title());descriptions.add(await page.locator('meta[name="description"]').getAttribute('content')||'');
 const links=await page.locator('a[href]').evaluateAll(els=>els.map(el=>el.getAttribute('href')!));links.filter(href=>href.startsWith('/')&&!href.startsWith('//')).forEach(href=>targets.add(href.split('?')[0]));
 const imgs=await page.locator('img[src]').evaluateAll(els=>els.map(el=>el.getAttribute('src')!));for(const src of new Set(imgs))expect((await request.get(src)).status(),src).toBe(200);
 }
 expect(titles.size).toBe(22);expect(descriptions.size).toBe(22);for(const target of targets)expect((await request.get(target)).status(),target).toBe(200);expect(errors).toEqual([]);
 expect((await page.goto('/paquetes/no-existe'))?.status()).toBe(404);await expect(page.locator('h1')).toContainText('Volvamos');
});
test('sin overflow en 320,390,768,1024 y1440',async({page})=>{
 for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:900});for(const route of routes){await page.goto(route);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width} ${route}`).toBeTruthy();}}
});
test('filtros de paquetes y galería, diálogo, teclado y comparador',async({page})=>{
 await page.goto('/paquetes');await page.getByRole('button',{name:'Grupos',exact:true}).click();await expect(page.locator('.package-card:visible')).toHaveCount(2);await expect(page.getByRole('button',{name:'Grupos',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Todos',exact:true}).click();await expect(page.locator('.package-card:visible')).toHaveCount(7);
 await page.goto('/galeria');await page.getByRole('button',{name:'Novias',exact:true}).click();await expect(page.locator('.gallery-item:visible')).toHaveCount(2);const first=page.locator('.gallery-item:visible').first();await first.click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Cerrar imagen'})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await expect(first).toBeFocused();await page.locator('#comparison').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#comparison')).toHaveValue('51');await expect(page.locator('.after')).toHaveCSS('clip-path','inset(0px 0px 0px 51%)');
});
test('menú móvil y FAQ con teclado',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');const menu=page.getByRole('button',{name:'Menú'});await expect(menu).toHaveAttribute('aria-expanded','false');await menu.click();await expect(page.getByRole('navigation')).toBeVisible();await page.keyboard.press('Escape');await expect(menu).toHaveAttribute('aria-expanded','false');await expect(menu).toBeFocused();await page.goto('/preguntas-frecuentes');const summary=page.locator('summary').first();await summary.focus();await page.keyboard.press('Enter');await expect(page.locator('details').first()).toHaveAttribute('open','');
});
async function eventStep(page:import('@playwright/test').Page){await page.locator('#fecha').fill(today());await page.locator('#hora').fill('17:30');await page.locator('#lugar').fill('Ciudad, distrito');}
test('CTA, mínimos, validación XV, revisión y volver sin perder datos',async({page})=>{
 await page.goto('/paquetes/sweet-xv-party');await page.getByRole('link',{name:'Consultar Sweet XV Party'}).click();await expect(page.locator('#paquete')).toHaveValue('sweet-xv-party');await expect(page.locator('#personas')).toHaveValue('4');await expect(page.locator('#evento')).toHaveValue('quinceanero');await eventStep(page);
 await page.locator('#personas').fill('3');await page.getByRole('button',{name:'Continuar'}).click();await expect(page.locator('#error-personas')).toContainText('entre 4');await page.locator('#personas').fill('4');await page.getByRole('button',{name:'Continuar'}).click();await expect(page.locator('#responsable')).toBeVisible();await page.locator('#nombre').fill('   ');await page.locator('#telefono').fill('+51 999 123 456');await page.getByRole('button',{name:'Revisar consulta'}).click();await expect(page.locator('#error-nombre')).toContainText('Escribe');await expect(page.locator('#error-responsable')).toContainText('responsable');await expect(page.locator('#error-consentimiento')).toContainText('Autoriza');
 await page.locator('#nombre').fill('María Ñúñez');await page.locator('#responsable').fill('Ana Núñez');await page.locator('#notas').fill('Ondas & un tocado <delicado>');await page.locator('#consentimiento').check();await page.getByRole('button',{name:'Revisar consulta'}).click();await expect(page.locator('#booking-summary')).toContainText('María Ñúñez');await expect(page.locator('#package-summary')).toContainText('Maquillaje social para mamá y dos acompañantes');await expect(page.locator('#whatsapp-link')).toBeHidden();await expect(page.locator('#prepared-message')).toContainText('no confirma la reserva');await expect(page.locator('#prepared-message')).toContainText('Ondas & un tocado <delicado>');
 await page.getByRole('button',{name:'Editar contacto'}).click();await expect(page.locator('#nombre')).toHaveValue('María Ñúñez');await expect(page.locator('#notas')).toHaveValue('Ondas & un tocado <delicado>');await page.getByRole('button',{name:'Volver'}).click();await expect(page.locator('#fecha')).toHaveValue(today());await expect(page.locator('#lugar')).toHaveValue('Ciudad, distrito');
});
test('fecha pasada, espacios, personalización y cambio de paquete',async({page})=>{
 await page.goto('/reservar?paquete=social');await page.locator('#fecha').fill('2020-01-01');await page.locator('#hora').fill('10:00');await page.locator('#lugar').fill('   ');await page.locator('#personas').fill('1.5');await page.getByRole('button',{name:'Continuar'}).click();await expect(page.locator('#error-fecha')).toContainText('hoy');await expect(page.locator('#error-lugar')).toContainText('ciudad');await expect(page.locator('#error-personas')).toContainText('entero');await eventStep(page);await page.locator('#personas').fill('1');await page.locator('#servicio').selectOption('ambos');await page.getByRole('button',{name:'Continuar'}).click();await expect(page.locator('#error-personalizar')).toContainText('Confirma');await page.locator('#personalizar').check();await page.getByRole('button',{name:'Continuar'}).click();await expect(page.locator('#nombre')).toBeVisible();await page.getByRole('button',{name:'Volver'}).click();await page.locator('#paquete').selectOption('bridal-luxury');await expect(page.locator('#personas')).toHaveValue('3');await expect(page.locator('#servicio')).toHaveValue('ambos');await expect(page.locator('#evento')).toHaveValue('matrimonio');await expect(page.locator('#package-hint')).toContainText('Actualizamos');
});
test('copia y fallback sin envío',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto('/reservar?paquete=social');await eventStep(page);await page.getByRole('button',{name:'Continuar'}).click();await page.locator('#nombre').fill('Ana');await page.locator('#telefono').fill('+1 (202) 555-0198');await page.locator('#consentimiento').check();await page.getByRole('button',{name:'Revisar consulta'}).click();await page.getByRole('button',{name:'Copiar mi consulta'}).click();await expect(page.locator('#copy-status')).toContainText('Consulta copiada');expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('Hola AURA, deseo consultar disponibilidad.');
 await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{value:()=>Promise.reject(new Error('blocked'))}));await page.getByRole('button',{name:'Copiar mi consulta'}).click();await expect(page.locator('#message-details')).toHaveAttribute('open','');await expect(page.locator('#prepared-message')).toBeFocused();
});
test('reglas de consulta y codificación internacional',()=>{
 const valid:Booking={evento:'evento',paquete:'social',fecha:today(),hora:'12:00',personas:'1',servicio:'maquillaje',modalidad:'estudio',lugar:' Ciudad ',nombre:' María ',responsable:'',telefono:'+51 (999) 123-456',notas:'Piel luminosa & ondas <suaves>',consentimiento:true,personalizar:false};
 expect(validateEvent(valid)).toEqual({});expect(validateContact(valid)).toEqual({});const message=makeMessage(valid);expect(whatsappURL(message)).toBeNull();const url=whatsappURL(message,'51999123456')!;expect(new URL(url).searchParams.get('text')).toBe(message);expect(url).toContain('%0A');expect(url).toContain('%C3%AD');expect(whatsappURL(message,'número pendiente')).toBeNull();expect(initialBooking(new URLSearchParams('paquete=no&evento=hack&servicio=eventos'))).toEqual({paquete:'',evento:'',servicio:'ambos'});
 for(const p of packages){const initial=initialBooking(new URLSearchParams('paquete='+p.id));expect(initial.personas).toBe(String(packageRules(p).minPeople));expect(validateEvent({...valid,...initial})).toEqual({});}
 for(const phone of ['1234567','1234567890123456','abc +51 999123456'])expect(validateContact({...valid,telefono:phone}).telefono).toBeTruthy();for(const count of ['0','31','1.5'])expect(validateEvent({...valid,personas:count}).personas).toBeTruthy();
});
